### PR TITLE
Update external projects

### PR DESCRIPTION
**Pull request by jcfr**
* Update default Qt version from 4 to 5
* Remove obsolete workaround including CTestUseLaunchers
* Remove unmaintained integration of KWStyle
* Remove unmaintained and unused OpenIGTLink external project
* Remove unmaintained and unused ZMQ external project
* Update ITK from `v3.20.1` to `v5.1.2`
* Update QtTesting to support building against C++98
* DMCTK
  * Update DCMTK from `DCMTK-3.6.1_20161102` to `DCMTK-3.6.5` 
  * Update DCMTK from DCMTK-3.6.5 to patched-DCMTK-3.6.6_20210115
  * Update DCMTK to fix CMP0115 CMake warnings
  * Disable DCMTK ICU default for Superbuild
* VTK
  * Fix git repository URL used in VTK external project
  * Update VTK to v8.0.1 to support Qt4, to v9.2.2 to support Qt5

### CODE REVIEW

**Comment by jcfr** [comment]
I did not update VTK as the current external  project aims to support both Qt4 and Qt5 and in Slice we removed Qt4 support a while back. 

For reference,  here is a prior discussion where we briefly discussed removing support for Qt 4.x, see https://github.com/commontk/CTK/pull/822#issuecomment-416983907

**Review by dzenanz — APPROVED** [review]

**Comment by jcfr** [comment]
Local build reported error with VTK:

```
Cloning into 'VTK'...
fatal: unable to connect to vtk.org:
vtk.org[0: 192.168.115.100]: errno=Connection refused

```

I will update it as well ...

**Comment by lassoan** [comment]
> I did not update VTK as the current external project aims to support both Qt4 and Qt5 and in Slice we removed Qt4 support a while back.

Users can use whatever versions they need, but we can still set Qt 5 and VTK 8 or 9 as default when someone does not specify any VTK and Qt versions.

**Comment by jriesmeier** [comment]
FYI: [DCMTK 3.6.6](https://blog.jriesmeier.com/2021/01/dcmtk-3-6-6-available-for-public-release/) has been released only recently.

**Pull request merged**
