### PR TITLE
ENH: Added filtering and multi-file export to DICOM metadata dialog

### PR DESCRIPTION
**Pull request by lassoan**
To further improve ability to collect DICOM metadata information from users, the following features were added to the DICOM metadata window:
- free-text search in tag, name, vale fields
- export of filtered results (useful for easily excluding patient identifiable information)
- exporting of tags in all files in the files list (useful for example for getting image position information that requires all values), it works combined with filtering
- expand/collapse of all branches
- show total number of files and 1-based file index
- resize column widths to content by default

GUI:
image

Example copy filtered metadata from all files in the series:

<pre>
images/1-270.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 55.500000	DS	34
images/10-268.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 10.500000	DS	34
images/11-198.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 4.500000	DS	32
images/12-171.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 64.500000	DS	34
images/13-248.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 67.500000	DS	34
images/14-257.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -40.500000	DS	34
images/15-287.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 73.500000	DS	34
images/16-183.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 16.500000	DS	34
images/17-258.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -22.500000	DS	34
images/18-157.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 46.500000	DS	34
images/19-046.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -10.500000	DS	34
images/2-295.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 70.500000	DS	34
images/20-147.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 22.500000	DS	34
images/21-089.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -43.500000	DS	34
images/22-230.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -25.500000	DS	34
images/23-124.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -19.500000	DS	34
images/24-150.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -58.500000	DS	34
images/25-155.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -31.500000	DS	34
images/26-216.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 1.500000	DS	32
images/27-001.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 7.500000	DS	32
images/28-011.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 37.500000	DS	34
images/29-260.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -16.500000	DS	34
images/3-031.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -64.500000	DS	34
images/30-280.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 40.500000	DS	34
images/31-167.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -7.500000	DS	34
images/32-175.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -49.500000	DS	34
images/33-026.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -13.500000	DS	34
images/34-106.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -55.500000	DS	34
images/35-177.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 43.500000	DS	34
images/36-021.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 34.500000	DS	34
images/37-264.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 49.500000	DS	34
images/38-212.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -73.500000	DS	34
images/39-156.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -67.500000	DS	34
images/4-177.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -1.500000	DS	34
images/40-005.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -70.500000	DS	34
images/41-273.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 61.500000	DS	34
images/42-185.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 13.500000	DS	34
images/43-196.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -46.500000	DS	34
images/44-208.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 28.500000	DS	34
images/45-227.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 25.500000	DS	34
images/46-142.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -34.500000	DS	34
images/47-229.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -4.500000	DS	34
images/48-295.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -37.500000	DS	34
images/49-031.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 31.500000	DS	34
images/5-147.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -61.500000	DS	34
images/50-202.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 52.500000	DS	34
images/6-195.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -52.500000	DS	34
images/7-229.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, -28.500000	DS	34
images/8-136.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 19.500000	DS	34
images/9-213.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 58.500000	DS	34
</pre>

### CODE REVIEW

**Comment by pieper** [comment]
Great idea! 👍

**Comment by lassoan** [comment]
Regexp filtering example:
image

**Comment by ihnorton** [comment]
This is great! (assuming it is scriptable from Python in Slicer, we could consider adding a dropdown box to the header viewer with "Metadata profiles" for pre-defined sets of tags of interest for specific data types)

**Comment by lassoan** [comment]
I've added method to get/set filter (there was already method to get the filtered results). I would think it would be mostly used for troubleshooting, so it's difficult to know in advance what sets of tags may make sense, but it can now be customized in Slicer before the popup window is shown (e.g., a reader plugin could specify a list of tags).

**Comment by lassoan** [comment]
Thanks for merging. I've updated git hash in Slicer (rev 26167).

**Comment by jcfr** [comment]
@lassoan You should now be able to merge PR.

**Pull request merged**
