### PR TITLE
ENH: Impove DIMSE widget

### PR DESCRIPTION
**Pull request by riep**
* Add collapsible button to hide DICOM server settings
* Only selected series are retrieved
fixes https://github.com/commontk/CTK/issues/993
Screenshot from 2021-08-26 20-14-22

### CODE REVIEW

**Comment by lassoan** [comment]
You can easily combine multiple filters, you can have as many input lines as you want, you just need to show one at each time and hide the others. It is true that with a combobox  you need two clicks to switch, so you may add a `<` and `>` buttons to go to the previous/next field.

**Comment by lassoan** [comment]
@riep I've updated this branch with a change that moves the search settings to the "Query" collapsible section and make the "Retrieve" section collapsible, too. The user can switch between these two sections (when one section is opened the other is closed automatically), so there is enough space for everything without the need to rework the search option widgets.

I've also updated tests that did not compile due to the changed API.

I've tested the retrieve of selected series and it worked well.

Please take a look, give it some testing and if you like it then I think we should merge this. Thanks for your contribution!

**Comment by riep** [comment]
Thanks Andreas! I was very busy lately so this PR was delayed. I test it next Monday and let you know.

**Comment by riep** [comment]
This is nice. I have to double-check the code and check the code format. Is there a specific way to apply format in CTK? 
Also, I thought that we could change the way the progress bar is updated. Do you think it would be OK to update the progress bar based on the number of series retrieved. Currently, the progress bar provides limited information on the remaining retrieve time.

**Comment by lassoan** [comment]
> Is there a specific way to apply format in CTK?

I don't think there is a format specification file. However, the amount of modified code is so little that it should not be hard at all to fix up any formatting issues manually.

>  I thought that we could change the way the progress bar is updated. Do you think it would be OK to update the progress bar based on the number of series retrieved. Currently, the progress bar provides limited information on the remaining retrieve time.

Do you find the current progress bar too detailed or too high-level?
For long operations it is common to have double progress bar - overall progress (x out N series completed) and progress of the current step (x% of the current series is completed).

**Comment by riep** [comment]
ok, I would be nice to have a double progress bar. That could be part of another feature and PR. I do the code formatting and testing today.

**Comment by riep** [comment]
It looks good to me and should be ready to be merged.

**Pull request merged**
