### PR TITLE
ENH: Update minimum Qt4 to 4.7

### PR DESCRIPTION
**Pull request by phcerdan**
This allow to remove the definition QFILEDIALOG_OPTIONS
in ctkDirectoryButton and ctkPathLineEdit, used to conserve
backwards compatibility.

### CODE REVIEW

**Comment by jcfr** [comment]
Consider fixing the build error: https://circleci.com/gh/commontk/CTK/405?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jcfr** [comment]
Nitpick: Two separate PR would be best. One updating minimum required version, and one updating the filedialog

**Comment by finetjul** [comment]
What is the benefit to get rid of the Qt 4.6 support ?

**Comment by jcfr** [comment]
This allows to easily move forward with https://github.com/commontk/CTK/pull/823 without having to add yet an other option.

**Comment by finetjul** [comment]
That does not seem like a strong motivation :-/ I wonder if some preprocessing macro (e.g. #if QT_VERSION < QT_VERSION_CHECK(...) ) wouldn't have worked around your issue.

There are other places in code that support code < 4.7 (search 0x040700 or 0x040600 in code)  you may also want to get rid of it.

**Comment by jcfr** [comment]
Thanks for the feedback :+1: 

> What is the benefit to get rid of the Qt 4.6 support ?

Simplify and reduce cost associated with maintenance. Qt 4.6 was first release almost [10 years ago](https://en.wikipedia.org/wiki/Qt_version_history) ... 


> I wonder if some preprocessing macro (e.g. #if QT_VERSION < QT_VERSION_CHECK(...) ) wouldn't have worked around your issue.

That is also an option. It is is not too late to revert the change and continue  support Qt 4.6.

Are you suggesting we continue support it ? 

If we do so, I suggest we create a docker image with Qt 4.6 (similar to the [one we have](https://github.com/Slicer/SlicerBuildEnvironment/blob/master/Docker/qt4-centos5/Dockerfile) for Qt 4.8).


> There are other places in code that support code < 4.7 (search 0x040700 or 0x040600 in code) you may also want to get rid of it.

Thanks for pointing this out.

**Comment by finetjul** [comment]
I'm suggesting to continue support Qt 4.6 if there is no strong reason to do so (-> the cost to support it is too "high"). In this issue, it did not seem that high too me (that was a first impression, without really looking at the issue).

Alternatively, the class (and the ones depending on it) could also be removed from the CTK compilation. That way Qt 4.6 is still supported (minus some widgets like this one).

**Comment by jcfr** [comment]
The issue is that we don't have a build of Qt 4.6 to test any of our changes.

Would it work if we revert the commit updating the minimum required version and do our best effort to not break the code but do not test it ?

**Comment by finetjul** [comment]
I guess it is fine :-) 
I think we can't require contributors to test CTK with every Qt version before pushing their code

Thanks for the revert !

**Pull request merged**
