### PR TITLE
Inserted parameters to the httpGet that the subjects and experiments have more attributes to show in applications.

### PR DESCRIPTION
**Pull request by danielknorr**
For MITK we would like to have some more informations of a subject or experiment.
So we need a httpGet with more parameters.
The default parameters are included.

(Again my pull request with a single commit. Without ID change. Compare #566 )

Best regards,

Daniel

### CODE REVIEW

**Comment by jcfr** [comment]
:+1: 

Can somebody with XNat expertise confirm ?

Ps: Ideally, commit title should be ~65chars. See http://commontk.org/index.php/Contributing_to_CTK#Git_Commit_Style

**Comment by danielknorr** [comment]
Ups! :baby: me!
Sorry for the long text. Next time I will do better!

**Comment by AndreasFetzer** [comment]
I have two remarks:
* Please use the static members for e.g. ID, NAME, etc.that are defined in the specific ctkXnatObject class
* I suggest to not add the existing properties like id, name, etc., hardcoded to the columns query parameter, but do it within a loop and then afterwards add the additional columns like gender, weight, etc.

**Comment by AndreasFetzer** [comment]
:+1: 
Changes look good to me!
@espakm could you also have a look at them?
If you don't see any obstacles, this pull request can be integrated

**Comment by AndreasFetzer** [comment]
@espakm I agree, we should keep imaging session specific code away from the more general experiment. 

I noticed that ctkXnatExperiment is of type xnat:experimentData, which is extended by xnat:subjectAssessorData in the XNAT data model. Consequently if we want to model the XNAT data model accurately, we would have to introduce classes for xnat:SubjectAssessorData, xnat:DerivedData, xnat:SubjectVariableData and xnat:ImageSessionData.

Another rather quick solution would be to simply introduce two new functions in the ctkXnatSubject:
One for fetching objects of type xnat:imageSessionData and one for xnat:subjectVariableData.
From an developer point of view this is the least flexible approach.

What do you think? I attached three images that depict the architecture of the XNAT data model, the current CTK architecture and the one I propose for CTK.
2015-11-xnat-data-model
2015-11-ctk-xnat-data-model
2015-11-proposed-ctk-xnat-data-model

**Comment by jcfr** [comment]
Look like @danielknorr did a good job addressing the comments. 

What is the status on this ? Should the redesign be addressed in a follow PR ?

**Comment by AndreasFetzer** [comment]
I suggest to address the redesign in a separate issue. As mentioned above, as a quick solution for this issue, I could simply introduce two new functions in the ctkXnatSubject:
* One for fetching objects of type xnat:imageSessionData
* and one for xnat:subjectVariableData
These two functions could then be called in the ctkXnatSubjects fetch function.

@espakm, @jcfr what do you think?

**Comment by AndreasFetzer** [comment]
I just added the quick-fix to my CTK fork. You can have a look at it [here](https://github.com/commontk/CTK/compare/master...AndreasFetzer:expand-columns-for-subject-and-experiment-quickfix)
If you are ok with the changes I can create another pull request.

**Comment by jcfr** [comment]
Nice.

https://github.com/commontk/CTK/commit/36864f8104b9a127ae887080bda208ff307a1057 looks good but let's wait for feedback from @espakm  and @danielknorr before integration.

**Comment by AndreasFetzer** [comment]
Daniel Knorr was a student who worked on the XNAT support for MITK. Since he is no longer working at our department, I am taking care of his pull requests.

**Comment by jcfr** [comment]
Great. Thanks for the note.

**Comment by espakm** [comment]
It is good to split the fetch function so that you can retrieve more information specific to experiment categories.

What regards the type hierarchy, your point is valid. The current mapping is incorrect and incomplete. I would rename ctkXnatAssessor to ctkXnatImageAssessor to avoid eventual confusion with subject assessors that are on the same level in the hierarchy. (The current naming would suggest that ctkXnatAssessor is more generic than ctkXnatSubjectAssessor.)

Thanks very much!

**Pull request merged**
