### PR TITLE
Improve external dependency handling

### PR DESCRIPTION
**Pull request by saschazelzer**
Using an externally build DCMTK with CMAKE_DEBUG_POSTFIX set to "d" led to problems in the CTK CMake scripts.

Further, targets from external projects build within the CTK superbuild were not available when calling find_package(CTK). For example, the CTKXNATCore library depends on qRestAPI and when linking an external library to CTKXNATCore, CMake computes the transitive link dependency and links qRestAPI as well. However, there is no imported target available which leads to "library not found" errors thrown by the linker.

### CODE REVIEW

**Comment by saschazelzer** [comment]
@jcfr Would you mind reviewing my changes please?

**Comment by saschazelzer** [comment]
@jcfr I changed the PR according to your suggestions and also handle the variables in CTKConfig.cmake now differently for build and install trees. What do you think?

**Comment by jcfr** [comment]
:+1:

**Comment by saschazelzer** [comment]
Thanks for the good discussion :-)

**Pull request merged**
