### PR TITLE
4236 python console perfect autocomplete rebased

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@MayeulChassagnard There are few issue with this topic.

Details are reported here: http://na-mic.org/Mantis/view.php?id=4236#c14067

Also copied below for convenience:

4236_autocomplete_parenthesis_1

=> in this case, `bar_instance_member` is missing


4236_autocomplete_parenthesis_2

=> in this case, autocompletion is correct

**Comment by jcfr** [comment]
As a side note, the class method should be declared using `@staticmethod` decorator.

**Comment by MayeulChassagnard** [comment]
I was thinking of an other case.

If we do Foo().bar_instance_method(). [TAB], should it make appear BAR_CLASS_MEMBER, bar_class_method(),  bar_instance_member and bar_instance_method()? 

I guess the answer is no because completing with any of those stuff produce an error.

**Comment by jcfr** [comment]
Only existing and valid attributes should be suggested

If you make sure to evaluate the code after [this](https://github.com/jcfr/CTK/blob/090362b522d8e35842b1d68f99f51b625b36c066/Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp#L397) line, it should allow you to get a reference to the last object.

If there is no valid option, nothing should happen.

**Comment by jcfr** [comment]
@MayeulChassagnard  Here is the topic where I did some experiments: https://github.com/commontk/CTK/compare/master...jcfr:4236-save-interactive-position

**Comment by jcfr** [comment]
Superseded by #https://github.com/commontk/CTK/pull/671

**Pull request closed without merging**
