### PR TITLE
Update ctkLogger

### PR DESCRIPTION
**Pull request by jcfr**
* Update `ctkLogger` adding support for log level: Set default level based on the build config.
* Update `ctkErrorLogLevel` enum values defining "Unknown" as 0

### CODE REVIEW

**Comment by jcfr** [comment]
@Punzo @lassoan There changes were originally part of https://github.com/commontk/CTK/pull/1165 and have been factored out into an independent pull request.

**Comment by jcfr** [comment]
Now that we removed support for Qt4, for new classes, I think we should instead standardize on using `QLoggingCategory` and avoid `ctkLogger`.

See https://doc.qt.io/qt-5/qloggingcategory.html

**Comment by Punzo** [comment]
> [@Punzo ](/Punzo) [ @jcfr ](/jcfr)
> ` [ENH: Update ctkErrorLogLevel enum value setting "Unknown" as 0](/commontk/CTK/pull/1181/commits/2a8f6e13c2e8cda9340589c0e81f434578fa03e8)`

ok, perfect!

**Comment by jcfr** [comment]
I revisited the default level associated with the ctkLogger functions and also added a multiple tests.

**Pull request merged**
