### PR TITLE
Improve ctkVTKHistogram metaobject for better pythonqt wrapping

### PR DESCRIPTION
**Pull request by jcfr**
@ayarmarkovich Please test and let us know how it works.

### CODE REVIEW

**Comment by ayarmarkovich** [comment]
The fix worked:  ctk.ctkVTKHistogram().setDataArray() can be used in python.
Would like to fix python wrapping for ctkTransferFunctionBarsItem

**Comment by ayarmarkovich** [comment]
It looks like changes are working. Please integrate into slicer SB.

**Comment by jcfr** [comment]
:+1: Thanks for testing

**Comment by jcfr** [comment]
Would be great if you do a test build of Slicer with CTK hash set to 6e246f34b0a313497626ae1203ad49864fcb8421. Would be good to check that the recent change to external project handling in CTK don't cause any issue.

**Pull request merged**
