### PR TITLE
BUG: Fixed memory corruption in histogram computation

### PR DESCRIPTION
**Pull request by lassoan**
When scalar range is incorrectly set for an image data (e.g., specified incorrectly in the image header)
then out-of-range indexes were computed during histogram computation, which caused memory corruption.

Fixed the problem by adding range check before using the index.

### CODE REVIEW

**Comment by lassoan** [comment]
See this discussion for info on how this problem causes crash in 3D Slicer: https://discourse.slicer.org/t/crash-when-using-volumes-module-on-windows-7-after-4-9-version/1711/6

**Comment by lassoan** [comment]
I'm not sure what is the best way to fix this. Should we log a warning? Should we always ignore scalar range?

**Comment by pieper** [comment]
LGTM

Thanks @lassoan for figuring this out and patching CTK 👍 

To be technically correct and robust we should probably be recalculating the scalar range before determining the bins.  Also statistically estimating the histogram would make this faster and would almost always be good enough.  But those could be changes in the future.

**Comment by pieper** [comment]
Tested with data that caused crash without this fix but works fine with this fix.

**Pull request merged**
