### PR TITLE
Fix build issues with Qt > 5.14

### LINKED ISSUE #898: Qt 5.14 support
```
CTK-build/Libs/Widgets/moc_ctkCoordinatesWidget.cpp:184:5: error: cannot convert ‘const QMetaObject* const*’ to ‘const QMetaObject::SuperData*’ in initialization
  184 |     qt_meta_extradata_ctkCoordinatesWidget,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     |
      |     const QMetaObject* const*

```

### PR DESCRIPTION
**Pull request by cnd**
Closes #898

### CODE REVIEW

**Comment by lassoan** [comment]
Q_SLOTS/Q_SIGNALS are safer versions of signals/slots that are recommended to be used in libraries that may be used with combination of other libraries to avoid name conflicts (https://doc.qt.io/qt-5/signalsandslots.html#using-qt-with-3rd-party-signals-and-slots). I would consider usage of Q_SLOTS/Q_SIGNALS macros in CTK are justified and changing the few occurrences where signals/macros keywords are used directly.

If changing Q_SLOTS->slots and Q_SIGNALS->signals solved a build problem then most likely some headers are not included or not included in the right order. It would be great if you could solve the build error while keeping the current macros.

**Comment by cnd** [comment]
I'd keep it as local patch for now in that case

**Comment by lassoan** [comment]
> I'd keep it as local patch for now in that case

That's too bad. Finding out what #include you need to add sounds like a much smaller task than maintain your own fork. Anyway, when we'll get to upgrade to Qt-5.14 it'll be good to know that we can expect this error and there is pointer towards a solution.

**Comment by cnd** [comment]
@lassoan I actually can't understand so far why changing Q_SLOTS to slots fixes that build error, it even seems to me like some Qt bug, do you have some guess what is the real problem with it?

**Comment by lassoan** [comment]
Since other classes that uses Q_SLOTS has no build problem, these classes have something special about them. If you don't find anything obvious then you can replace the content with content of another class that has Q_SLOTS in it and change l it back to the original content of the file line-by-line and see what breaks the compilation and fix that (most likely some very trivial issue).

**Comment by lassoan** [comment]
CTK master can now be built using Qt-5.15.0

**Pull request closed without merging**
