### PR TITLE
ENH: Minor improvements for the visual DICOM browser

### PR DESCRIPTION
**Pull request by Punzo**
Apply high priority feedback from Andras from https://github.com/Slicer/Slicer/pull/7525#pullrequestreview-1811749078

I will mark this PR when I will have finished

### CODE REVIEW

**Comment by Punzo** [comment]
@lassoan this is needed for https://github.com/Slicer/Slicer/pull/7525

**Review by lassoan — APPROVED** [review]
Thanks a lot, this looks good to me. I've added a few minor issues to https://github.com/commontk/CTK/issues/1162.

**Comment by lassoan** [comment]
@jcfr I don't have force-push permission for this repository. Could you merge this PR, squashing this commit with @Punzo's other Visual DICOM browser commits? Thank you!

**Comment by jcfr** [comment]
I will take of this in the coming hour 👌

**Comment by lassoan** [comment]
Great, thank you!

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/commontk/CTK/pull/1165

**Pull request closed without merging**
