### PR TITLE
Fixed python wrapping to use qt5 with PythonQT qt5 version from sourcefo...

### PR DESCRIPTION
**Pull request by eric-h**
Our application depends on Qt5 and uses the ctk python wrapping with PythonQt. We propose a fix to use the new PythonQT 3.0 from sourceforge with ctk and qt5 fixes for the ctkPythonWrapping. If the PYTHONQT_INSTALL_DIR is set during superbuild CTK will try to use an external PythonQT else the build process will remain the same.

### CODE REVIEW

**Comment by nolden** [comment]
@jcrf could you please review this. It would help us to move on with the MITK-Qt5-Python integration. Currently the patch only supports an externally built PythonQt 3 for CTK, but I suggest we postpone the full superbuild integration until PythonQt 3 supports CMake, currently it only provides a qmake pro file.

**Comment by nolden** [comment]
@jcfr @jcrf Sorry, mixed some letters ...

**Comment by pieper** [comment]
+1 this would be great.  I'd love to see slicer support Qt5 as well (not
sure what else would need changing, but this would be a great start)

**Comment by jcfr** [comment]
@eric-h Thanks for your contribution.  Few minor issue to address and it should be good.

On last thing, could you also add a `message(FATAL_ERROR "To build CTK with Qt >= 5 and wrapping enabled, you are currently required to provide your own PythonQt by re-configuring CTK with option -DPYTHONQT_INSTALL_DIR:PATH=/path/to/PythonQt-30-install")`.

This should be added here: https://github.com/commontk/CTK/blob/59dfc7f24b0355be907a030a351fbd9f065794bf/CMakeExternals/PythonQt.cmake#L35

**Comment by eric-h** [comment]
The Qt5::Widgets dependency is needed, since there are C++ classes generated by the ctkWrapPythonQt.py script that  include QWidget.

**Comment by jcfr** [comment]
Thanks for the quick answer. 

Since `ctkWrapPythonQt.py` generates the decorators based on the list of classes available in each Libs folder (Libs/Core, Libs/Widget, ... ), do you know which generated classes require Qt5::Widget ? I just want to make sure to understand what lead to that requirement.

**Comment by eric-h** [comment]
The generated headers with QWidget are:
org_commontk_CTKCore.h
org_commontk_CTKDICOMCore.h
org_commontk_CTKPluginFramework.h

**Comment by jcfr** [comment]
@eric-h I just pushed a new topic including your changes. See https://github.com/commontk/CTK/compare/master...jcfr:fix-python-qt5

Would be great if you could test and let me know how it goes.

**Comment by eric-h** [comment]
@jcfr I just tested your branch. It works fine for us.

**Comment by jcfr** [comment]
Great, thanks for the follow up :+1:  Before integrating, could  you also comment on https://github.com/commontk/CTK/compare/master...jcfr:fix-python-qt5#commitcomment-10113444 ?

**Comment by eric-h** [comment]
Adding the ${PYTHONQT_INSTALL_DIR}/src dir was needed in the search path since the PythonQt 3.0 doesn't build with cmake and had no standard install/include folder, depending on if the QtCreator project is used on Linux or Visual Studio on windows the PythonQt.h header can end up in build/src rater than in build/include where it should be.

**Comment by jcfr** [comment]
Et voila.
Fixed in 9ad3253f123ceec5247a147db1c9d1ee688fdbdb

**Pull request closed without merging**
