### PR TITLE
Add qt to vtk image

### PR DESCRIPTION
**Pull request by lassoan**
Add utility function to convert Qt image to VTK image and fix a few Python wrappings.

### CODE REVIEW

**Comment by finetjul** [comment]
A QImage may not be RGBA, it has multiple pixel formats.

**Comment by finetjul** [comment]
Alternatively, you may want to use [vtkQImageToImageSource](https://github.com/Kitware/VTK/blob/master/Rendering/Qt/vtkQImageToImageSource.h)

**Comment by lassoan** [comment]
I've tried to use vtkQImageToImageSource first. First problem was that the filter was not wrapped by VTK's Python wrapper. I've tried to add a wrapping around it from CTK, but it turned out it was not included in VTK_LIBRARIES. Instead of blindly adding one more dependency, I had a look at the vtkQImageToImageSource implementation and realized that the filter is overcomplicated and the operation can be implemented in a few lines of code and so it is not worth using vtkQImageToImageSource.

**Comment by finetjul** [comment]
Fair enough

**Comment by lassoan** [comment]
> QImage may not be RGBA, it has multiple pixel formats.

We call `inputQImage.convertToFormat(QImage::Format_RGBA8888)`, to get an RGBA image.

**Comment by finetjul** [comment]
> > QImage may not be RGBA, it has multiple pixel formats.
> 
> We call `inputQImage.convertToFormat(QImage::Format_RGBA8888)`, to get an RGBA image.
Yep, I saw that afterwards.

That's good with me then.

**Comment by pieper** [comment]
Do you plan to replace the corresponding code that's already in Slicer?

https://github.com/Slicer/Slicer/blob/a02f79c7c788708a3dccfeb9ff4df76b6a5868be/Libs/MRML/Widgets/qMRMLUtils.cxx#L151-L205

**Comment by lassoan** [comment]
> Do you plan to replace the corresponding code that's already in Slicer?
>
> https://github.com/Slicer/Slicer/blob/a02f79c7c788708a3dccfeb9ff4df76b6a5868be/Libs/MRML/Widgets/qMRMLUtils.cxx#L151-L205

I've added this new function because I did not find it in Slicer (the closest was the one in CTK, which only provided conversion in the other direction).

I think it makes sense to have the feature available at the lowest-level library (and use that in higher-level libraries). So, I would move the best implementation of the converters to CTK and use that from qMRMLUtils.

**Comment by lassoan** [comment]
Thanks for the reviews. I've consolidated with the implementations in Slicer, added a test, and merged.

**Pull request merged**
