### PR TITLE
xnat resource uri with name integration

### PR DESCRIPTION
**Pull request by AndreasFetzer**
This pull request replaces pull request #574
Cleaned up commit message and create integration branch for master merge.

### CODE REVIEW

**Comment by jcfr** [comment]
:+1:

**Comment by espakm** [comment]
:+1:

**Comment by AndreasFetzer** [comment]
@jcfr @espakm 
If you are ok with the proposed changes, could one of you merge this?
Thank you very much!

**Comment by espakm** [comment]
I have no rights to merge. JC, please?

**Pull request merged**
