### PR TITLE
BUG: Fixed console paste bug

### PR DESCRIPTION
**Pull request by cpinter**
The command buffer was not updated after pasting, which resulted the end of command not being propagated to the buffer.

Also fixed typos and stylistic issues, removed commented out code

Fixes https://github.com/commontk/CTK/issues/736

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks @cpinter 👍 

I will test and integrate shortly.

**Comment by cpinter** [comment]
Cc: @jcfr

Please check this out. It is supposed to fix a bug I reported https://github.com/commontk/CTK/issues/736
Thanks!

**Comment by cpinter** [comment]
Excellent, thanks!

**Comment by jcfr** [comment]
As a side note, it looks like there is a typo in your last name. See https://github.com/commontk/CTK/commit/a2e623a25ea4b1038957512b0b34c76775bab2b9.patch

**Comment by jcfr** [comment]
Closing. Integrated in https://github.com/commontk/CTK/commit/8c4bed5872fce4fd03de49caf7c7d3d78fbd4823

**Comment by cpinter** [comment]
Thanks Jc! You really review thoroughly, I'll fix that last name thing for my CTK clone :)

**Pull request closed without merging**
