### PR TITLE
Fix PythonLibs handling

### PR DESCRIPTION
**Pull request by kislinsk**
1. The FindPythonLibs module reads PYTHON_LIBRARY as a hint but it also sets the same variable when successful. In the latter case, the variable may be set to a list containing target_link_libraries
keywords like "optimized" and "debug" instead of a single filepath. When read as a hint, though, FindPythonLibs only understands a single filepath. Repeated unguarded calls to the module may result in a faulty value of PYTHON_LIBRARY like "optimized;optimized;python3.lib;debug;debug;python3d.lib". Such values entail errors when the linker tries to link against the keywords "optimized" or "debug".
2. PYTHON_LIBRARY may be a mixed list of keywords and filepaths and should not be used directly in get_filename_component()
3. Same for passing PYTHON_LIBRARY to PythonQt.
4. The documented output variable of FindPythonLibs is PYTHON_LIBRARIES instead of PYTHON_LIBRARY, which is an old relict from pre CMake 3.0 (minimal required CMake version of CTK).

### CODE REVIEW

**Comment by kislinsk** [comment]
Fixed a wrong iterator name I introduced in a last-minute change.

**Comment by kislinsk** [comment]
This PR still is not complete, sorry. I just run into a debug linker problem on Windows with CTKScriptingPythonCore for the first time. Eventhough python37_d.lib is set as link dependency something wants to draw in python37.lib. Investigating...

**Comment by kislinsk** [comment]
> This PR still is not complete, sorry. I just run into a debug linker problem on Windows with CTKScriptingPythonCore for the first time. Eventhough python37_d.lib is set as link dependency something wants to draw in python37.lib. Investigating...

In fact, when linking against python37.lib instead of python37d.lib, everything works fine.

**Comment by lassoan** [comment]
Thank you for working on this, I don't fully understand the details but it's great if you fix such inconsistencies.

Note that we often need to use release-mode Python binaries in applications built in debug-mode because third-party binary packages are only available for release-mode Python. Please make sure that this will remain possible.

**Comment by kislinsk** [comment]
> Note that we often need to use release-mode Python binaries in applications built in debug-mode because third-party binary packages are only available for release-mode Python. Please make sure that this will remain possible.

No worries, last fix in the pull request is actually right what you describe: prefer using release-mode Python also in debug configuration as debug-mode Python has many implications. Seems to be the adopted standard in other Projects like Qt and Boost as well.

**Pull request merged**
