### PR TITLE
Improve qt 5 support

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by finetjul** [comment]
Does it mean CMAKE_PREFIX_PATH is no longer supported ?

**Comment by pieper** [comment]
Nice!

**Comment by jcfr** [comment]
> Does it mean CMAKE_PREFIX_PATH is no longer supported ?

Indeed. If needed, I can still make sure `CMAKE_PREFIX_PATH` is passed. Would that be helpful ?

**Comment by jcfr** [comment]
@finetjul  Let me know if that last commit would help. Thanks again for the review

**Comment by finetjul** [comment]
That would be nice to still support CMAKE_PREFIX_PATH indeed.
Thanks for the additional fix.

It's good for me then.

**Pull request closed without merging**
