### PR TITLE
Dicom speedup import

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by pieper** [comment]
LGTM.  I assume the failed CI is unrelated?

**Comment by jcfr** [comment]
> I assume the failed CI is unrelated?

@pieper Before integrating, let's fix the CI. This should do it: https://github.com/commontk/CTK/pull/741

**Comment by jcfr** [comment]
@lassoan  Here is the updated topic with your changes.

**Comment by lassoan** [comment]
Thank you, it looks good. We can tune it further as needed (move begin/end transaction code to helper methods, do the entire import in one transaction, etc).

**Pull request merged**
