### PR TITLE
resource uri with label

### PR DESCRIPTION
**Pull request by danielknorr**
To Create a subject or an experiment with a XNAT generated ID, the ID should not be used.
Therefore the resourceUri() method also can return the URI with the label of an Object.
Adjusted the TestCase to this change.

### CODE REVIEW

**Comment by AndreasFetzer** [comment]
Just as a remark:
The resourceUri method currently returns the URI containing the ID of a xnat object.
If the object is about be uploaded to the server, it doesn't have an ID yet of course.
* If you do not set the ID explicitly you will end up with an invalid http query.
* If you set one, you will end up with an undefined XNAT behaviour (see also https://groups.google.com/forum/#!topic/xnat_discussion/p98lMGvwVLY)

So returning the resourceUri using the label, if no ID is available is necessary, and from an XNAT point of view totally fine.

**Comment by jcfr** [comment]
@danielknorr @AndreasFetzer What is the status of the PR ?

**Comment by espakm** [comment]
Looks good to me but the last two commits should be squashed and "(the last commit was a mistake.)" should be removed from the last commit message. Thanks!

**Comment by AndreasFetzer** [comment]
I will take care of it the next few days. I will also provide an integration branch to avoid conflicts. Thanks for reviewing the changes!

**Comment by AndreasFetzer** [comment]
@jcfr Thank you for merging #612
With #612 this pull request is resolved as well.

**Comment by jcfr** [comment]
@AndreasFetzer Thanks for the note. Closing this PR.

**Pull request closed without merging**
