### PR TITLE
Error log widget improvements

### PR DESCRIPTION
**Pull request by jamesobutler**
This adds improvements to the Error Log such as:
- a new "Hide Table" button which allows viewing the log not in table format, but just simple text format. This is supported by selecting all fields when hiding the table. When hiding the table you can still use the filter buttons to view all errors in the simple text format as well.
- supporting colored text in the description column and full description fields. Warning (orange), Error and Critical (red)

Note: Coloring is based on the log level, so if you see where a warning from "stream" is in red it is because it was logged as Critical which gets the red color.

## Current
|image

## This PR
image
image
image

### CODE REVIEW

**Comment by finetjul** [comment]
Nice feature !

I have a few remarks though:
 - adding a new button makes the dialog quite large now. Maybe split into 2 lines ? (with "Hide Table" and "Clear" on first line). Or maybe a tool button without text but with a "Console" icon (or a spreadsheet icon)
 - I am not sure "Hide Table" is the best caption for the button though... Maybe "Console mode" or simply "Console".
 - Alternatively, how about: 
```[Clear button] View: O Console O Table  Filter: □ Error □ Warning □ Info ``` 
or 
```[toolButton] □ Error □ Warning □ Info [Clear button]```
 - I guess we could also move Error/Warning/Info buttons into a single checkable combobox/menu

**Comment by jamesobutler** [comment]
I think changing "Hide Table" to "Console Mode" would be a nice change. Or even an icon, as you suggested, that conveys console, but I'm not sure where best to get one that doesn't have any licensing requirements. Any guidance there would be helpful.

Regarding thinking the dialog is too large now, the two row idea won't really work best in Slicer in the docked widget (as seen in linked PR). I think combining some into a combobox entry also reduces the quick functionality of filtering.  How about replacing the "All" button with this new console mode button? The "All" button currently just sets errors, warnings, info buttons to the checked state and I would guess the button is infrequently used. Then the dialog could remain the same size.

**Comment by lassoan** [comment]
Instead of table view, it could be called "grouped" view. We may not even show the toggle button on the GUI, it could be just a property that could be set with a signal with an external widget or from application settings.

**Comment by finetjul** [comment]
I agree that the "All" button can be removed. 
For the icon, you could use SP_FileDialogListView or SP_FileDialogDetailedView
I like the idea to have a Q_PROPERTY that controls the visibility of all the error log widget buttons. That way, applications can hide all the buttons and add it's own buttons instead. Then it would make sense to rename the ctkErrorLogView into a ctkErrorLogView (in CTK, a widget is a View with additional GUI elements).

**Comment by jamesobutler** [comment]
- I've changed the button to "Console Mode" button and given it the SP_FileDialogDetailedView icon. 
- I've added Q_PROPERTY for all the buttons in the widget so that all buttons can easily have their button visibility state changed based on the application's preference. Therefore I've decided to maintain the "All" button option.
- I've resolved some issues with the Qt4 build failing. Continued support for Qt4 should probably be reconsidered moving forward since it has been 5 years since the last patch release of 4.8 was released.  Qt6 is scheduled for release at the end of this year.

image
image

**Comment by finetjul** [comment]
Sounds good, however it does not fix the width change. How about having "All" button (with inconsistent height) hidden by default ?

**Comment by finetjul** [comment]
I personally wouldn't have "Mode" in uppercase for the "Console Mode" caption. It is not an important word.

I now find it odd to have a "console" button that controls the visibility of the "table" widget.
Shouldn't there be a button (visible by default) to control the visibility of the "table" widget and a button (hidden by default) to control the visibility of the "console" widget ?

**Comment by jamesobutler** [comment]
> Sounds good, however it does not fix the width change. How about having "All" button (with inconsistent height) hidden by default ?

I was thinking the ability to hide any of the buttons solves the width issue. The minimum size when all are visible is shown in the images above.

> I personally wouldn't have "Mode" in uppercase for the "Console Mode" caption. It is not an important word.

I can change this.

> I now find it odd to have a "console" button that controls the visibility of the "table" widget.
> Shouldn't there be a button (visible by default) to control the visibility of the "table" widget and a button (hidden by default) to control the visibility of the "console" widget ?

The “Console mode” button doesn’t just hide/show the table widget. When in the checked state it also selects all the items in the table view to make the description area look like a console. There isn’t a true console widget. It is just a description area for the currently selected items in the table. If you just showed the table but not the description area you wouldn’t be guaranteed to see the full message as the table only shows a limited about of characters before using an ellipses. The description is there to show the full message and also to combine all currently selected messages.

**Comment by jamesobutler** [comment]
I've made the update "Console Mode" to "Console mode"
image

**Comment by finetjul** [comment]
> > Sounds good, however it does not fix the width change. How about having "All" button (with inconsistent height) hidden by default ?
> 
> I was thinking the ability to hide any of the buttons solves the width issue. The minimum size when all are visible is shown in the images above. How small does it need to be in the default state? Specific number of pixels?

I think CTK should provide good default value. And we all agreed that the "All" button is not very useful therefore to be hidden. That will have the benefit to make the default size of the widget reasonable.

>>I now find it odd to have a "console" button that controls the visibility of the "table" widget.
Shouldn't there be a button (visible by default) to control the visibility of the "table" widget and a button (hidden by default) to control the visibility of the "console" widget ?

>The “Console mode” button doesn’t just hide/show the table widget. When in the checked state it also selects all the items in the table view to make the description area look like a console. There isn’t a true console widget. It is just a description area for the currently selected items in the table. If you just showed the table but not the description area you wouldn’t be guaranteed to see the full message as the table only shows a limited number of characters before using an ellipses. The description is there to show the full message and also to combine all currently selected messages.

I do not see how what you say and what I say are incompatible. Ok to select ALL messages when Table view gets hidden. Optionally such behavior could be an additional Q_PROPERTY on the error log widget.

**Comment by jamesobutler** [comment]
I'm still confused why you think there should be an option to hide the description area.  If only showing the table, then the messages can become useless as you are not guaranteed to see all of the text for a given message because it only shows a certain number of characters in the description column for a given row.  That's why the description area is something that has to be required always.

**Comment by jamesobutler** [comment]
I've pushed the change to hide the "All" entries button by default.  Note, that this is different from the discussion about whether to add a show/hide for the description area.

**Comment by lassoan** [comment]
> I'm still confused why you think there should be an option to hide the description area

I agree. For me, two modes makes sense:

1. Table mode - see Windows event viewer:

image

2. Console mode - see Linux logs

For a live window, console mode may be more useful, as it is easier to interact with it and simpler to see the last log messages.

What might be useful for a console mode is to have a toggle button auto-scroll to the last message (when you scroll up, this auto-scroll should be disabled).

**Comment by finetjul** [comment]
> If only showing the table, then the messages can become useless as you are not guaranteed to see all of the text for a given message because it only shows a certain number of characters in the description column for a given row. That's why the description area is something that has to be required always.

I think the table should make sense to be used by itself (without description/console). Currently I admit it is not showing everything and it can not. But it should/could (I'm not asking you to do it :-) ) be improved though e.g. by showing all the text (maybe a Q_PROPERTY could control such behavior) , or maybe showing the entire text as a tooltip when overlaying the item...).

**Comment by finetjul** [comment]
> For me, two modes makes sense:

I don't see why it hurts to support the 3rd mode: Table view only. 
I agree that for Slicer it might not be useful, but I guess some apps could require only such Table View mode.

By default, I agree to have the "Console" button hidden; only the Table button is visible and toggled.

**Comment by jamesobutler** [comment]
>  but I guess some apps could require only such Table View mode.

I would suggest that this support for Table View only mode be added whenever an application actually needs that mode. I suggest this because additional work is needed to really support a good table view only mode such as showing the entire message somehow without the description area. Unfortunately I do not have the extra time to continue with this effort as I only do this in my free time and the work week has started again here following our Federal holiday yesterday.

**Comment by lassoan** [comment]
I think we all agree. This third table-only mode could work very well, too. It would be just more work to implement - it is not the same as just hiding the message details.

Thanks a lot @jamesobutler for working on this and @finetjul for your feedbacks.

**Comment by finetjul** [comment]
Sounds good to me to leave it as is.

**Comment by jamesobutler** [comment]
I've slightly modified my commit `ENH: Add color to Error and Warning description text in ctkErrorLogModel` so that the error color is defined by the QPalette specified BrightText color which is usually something like red because it usually contrasts well. In Slicer we technically don't use a pure red color, but use a slightly different shade of red for better readability in dark mode.

**Comment by cpinter** [comment]
> There isn’t a true console widget. It is just a description area for the currently selected items in the table.

Can you please confirm that incoming log messages are shown in the console part (i.e. the new items are auto-selected)?

Also, auto-scroll to bottom is essential - not sure if it's included already.

> I've pushed the change to hide the "All" entries button by default. Note, that this is different from the discussion about whether to add a show/hide for the description area.

As I remember, removing the All button has been part of the plan. That button has no real utility, as it toggles the other three buttons, which the user can always do (with at most two clicks instead of one).

Thanks a lot for working on this!

**Comment by cpinter** [comment]
Is there any justification for closing the ticket and deleting the branch? I think if nothing else, it would be good to add 1+ sentence about the why, for the record. Thanks.

**Pull request closed without merging**
