### PR TITLE
ENH: Add patient display field for last study date

### PR DESCRIPTION
**Pull request by cpinter**
Many times it is useful to be able to order patients with last study date. This display field has now been added.

### CODE REVIEW

**Comment by cpinter** [comment]
Great, thank you! Could you merge it please (or give me rebase access)?

**Comment by cpinter** [comment]
Thanks!

**Comment by cpinter** [comment]
By the way: do I have push access to the new Slicer repo or do I need to open a PR to update the hash?

**Comment by lassoan** [comment]
I think you have write access to Slicer/Slicer.

**Comment by cpinter** [comment]
I got this:
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "CommitCheck" is expected. At least 1 approving review is required by reviewers with write access.
To https://github.com/Slicer/Slicer.git
! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Slicer/Slicer.git'
```

**Comment by jcfr** [comment]
@cpinter You have write access but you need to publish a branch to your fork and then create a PR. After that, you could by pass the review process and directly merge because you are core developer. That said, we encourage everyone to go through the review process.

**Comment by cpinter** [comment]
Alright, interesting. When there is a non-trivial change, the review process makes a lot of sense. Many times, however, I commit a simple fix, or an update like this. If I need to do the overhead of creating a branch in my fork and push it, then it's just a little bit less administration than going through the normal PR process.

**Comment by cpinter** [comment]
That said, I don't have write access after all.

image

Please merge if found approppriate.

**Comment by lassoan** [comment]
You can directly push to your fork (you can specify any branch name on the fly) and click on the link that tortoisegit to open a PR, another click to submit the PR. Then anybody else can approve the PR and then merge the PR. We can disable the approval requirement if we find it annoying, but I would try to keep it. PR will be even more useful if more automatic testing is done.

**Comment by cpinter** [comment]
Sure, no problem. I just wanted to find out how things work now. Actually the need for approval for everybody is a good thing.

**Pull request merged**
