### PR TITLE
4236 python console autocompletion solved

### PR DESCRIPTION
**Pull request by MayeulChassagnard**
Every bugs linked to the autocompletion in the python Console are solved.

For more details about those problems, feel free to take a look to the issue [#4236](http://na-mic.org/Mantis/view.php?id=4236) on our BugTracker

### CODE REVIEW

**Comment by MayeulChassagnard** [comment]
The last thing to do could be to create a test verifying the good autocompletion.

**Comment by jcfr** [comment]
Nice. Will review in the coming days. Adding test would be good too.
Jc

**Comment by jcfr** [comment]
To ensure the CI system test the topic, consider rebasing this topic and push forcing.

Thanks
Jc

**Comment by MayeulChassagnard** [comment]
Rebase done. Able to be merged after #659

**Comment by jcfr** [comment]
Closing this PR. Superseded by #662

**Pull request closed without merging**
