### PR TITLE
ctkAbstractPythonManager: Clean up PythonQt before finalizing the Python interpreter

### PR DESCRIPTION
**Pull request by msmolens**
This commit moves the call to PythonQt's cleanup function to be before the call that finalizes the Python interpreter. The interpreter should still be running during PythonQt::cleanup() so that calls to Py_DECREF succeed.

Applying this change exposes problems in PythonQt, so the following PythonQt PRs should be applied before this:
https://github.com/commontk/PythonQt/pull/25
https://github.com/commontk/PythonQt/pull/26

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for your contribution :+1: 

Corresponding changes have been integrated in PythonQt `patched-5` and `patched-6` branch. 

Could you update this PR to include an update to `CMakeExternals/PythonQt.cmake` ?

**Comment by msmolens** [comment]
I updated the reference in `CMakeExternals/PythonQt.cmake` to commontk/PythonQt@f9c7e6a8e7c9ca7953b7128e820a81c93ed2cc56.

**Comment by jcfr** [comment]
Since the change e3f2bc0 depends on the PythonQt update. Could you inverse the order of the commits ? Or squash them together ?

**Comment by msmolens** [comment]
Good point. I changed the order of the two commits.

**Pull request merged**
