### PR TITLE
ENH: added Q_INVOKABLE to methods for python wrapping to work

### PR DESCRIPTION
**Pull request by ayarmarkovich**
Jc, please review and commit to slicer CTK

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for your contirbution.

After addressing these two comment, it should be good to go.

**Comment by ayarmarkovich** [comment]
OK, I removed extra Q_INVOKABLE. Could you integrate this into slicer?
Thanks,
Alex

**Comment by jcfr** [comment]
Thanks. Will integrate this afternoon when I am back in the office.

On Fri, Feb 13, 2015 at 12:37 PM, ayarmarkovich <notifications@github.com>
wrote:

> OK, I removed extra Q_INVOKABLE. Could you integrate this into slicer?
> Thanks,
> Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commontk/CTK/pull/539#issuecomment-74293290>.
>



-- 
+1 919 869 8849

**Comment by pieper** [comment]
+1

This is exactly the kind of helpful exchange that makes the pull requests and the "social coding" model work so well.  Have a great weekend!

**Comment by jcfr** [comment]
Integrated in [23971](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=23971)

**Comment by jcfr** [comment]
Thanks for your contribution :+1:

**Pull request closed without merging**
