### PR TITLE
Dicombrowser support import multiple dirs

### PR DESCRIPTION
**Pull request by jcfr**
This PR addresses [2014: allow selection of subset of directories for dicom import](https://issues.slicer.org/view.php?id=2014).

Here is the updated interface:

dicom-import-file-dialog

Features:
* Support for multi selection of DICOM directories
* Add enum `ctkDICOMBrowser::ImportDirectoryMode` with `ImportDirectoryCopy` and `ImportDirectoryAddLink`
* Introduction of new settings keys `DICOM/ImportDirectoryMode` and `DICOM/DontConfirmImportDirectory`
* Migrating of old settings named `MainWindow/DontConfirmCopyOnImport`
* Improve pythonic API adding `Q_PROPERTY`: `ImportDirectoryMode` and `SkipConfirmImportDirectory`

Cc: @fedorov @pieper @lassoan @cpinter

### CODE REVIEW

**Comment by pieper** [comment]
Nice improvements!  LGTM (didn't try)

**Comment by fedorov** [comment]
Much needed feature, looks great, thank you JC!

**Comment by fedorov** [comment]
One comment - why do you need this import confirmation at all? To me, this just adds unnecessary complexity. Import is not an irreversible operation, so if user clicks "import", I think it is safe to assume that the user indeed wants to import, and I do not see any reason to ask again.

**Comment by cpinter** [comment]
Looks nice, thanks!

A nitpick: "Skip import directory confirmation" is a negative statement (equivalent to "don't show confirmation"), something we do not normally allow.

I agree with @fedorov. In the light of https://issues.slicer.org/view.php?id=4360#c15257, if confirmation would be skipped by default (i.e. the "Show confirmation" would be off by default), then the second popup would not be that big of an issue (and it would not appear in a different screen than the first one because there would be no first one).

**Comment by lassoan** [comment]
I've been always importing multiple directories by selecting multiple directories in File explorer and dragging them to the application screen. Unfortunately, Slicer kept showing the "copy/link" and "number of imported patients/studies/series" popups for each folder. Does this development addresses that issue as well?

**Comment by jcfr** [comment]
> Unfortunately, Slicer kept showing the "copy/link" and "number of imported patients/studies/series" popups for each folder. Does this development addresses that issue as well?

@lassoan  This is addressed by the use of `onImportDirectories` in Slicer instead of `onImportDirectory`. (aka a batch import)

>  A nitpick: "Skip import directory confirmation" is a negative statement (equivalent to "don't show confirmation"), something we do not normally allow.

@cpinter  The proposed implementation is "matches" the API of `ctkMessageBox`. I could have "Show import directory confirmation" checkbox .. but its value would be opposed to the one displayed in the confirmation dialog.

> why do you need this import confirmation at all?

I kept the original idea ... 

That said, considering we now have multi selection .. it gives an opportunity to quickly abort and update the selection.

Moving we could also display a summary of what would be imported (number of folders, etc ...)

**Comment by fedorov** [comment]
> I kept the original idea ...

I guess by the "original idea" you mean that even though user has a checkbox for "Copy on import" in the current import DICOM dialog, the user is asked one more time whether they want to copy or import in the confirmation popup.

I am not sure what motivated the original idea. I find Slicer to be quite busy with popups, and this development may be a good opportunity to get rid of one. I don't see a need for this secondary prompt. I understand secondary confirmation is important for operations that are irreversible, or potentially dangerous, but in this situation I am struggling to justify it.

**Comment by jcfr** [comment]
> why do you need this import confirmation at all [...]  I am struggling to justify it.

I am removing it then.

**Comment by fedorov** [comment]
@jcfr I expressed my view on this, but perhaps other folks have a good argument against it.

@lassoan @cpinter @pieper do you have any concerns about removing the confirmation popup?

**Comment by lassoan** [comment]
The popup does not seem to be necessary. It would be better to remove it.

**Comment by pieper** [comment]
Agreed - I think it's leftover from the earliest implementation of ctkDICOM and can be removed.

**Comment by cpinter** [comment]
> The proposed implementation is "matches" the API of ctkMessageBox. I could have "Show import directory confirmation" checkbox .. but its value would be opposed to the one displayed in the confirmation dialog.

What you say was my point exactly with https://github.com/Slicer/Slicer/pull/767. A decision has been made there about this, and I think if there was a consensus, then we should treat it as a convention.

@fedorov I agree with you. I never felt that confirmation dialog useful, only when it showed "0 series, 0 studies, ...". I think that dialog can be removed, but an error message on failed import would be still useful.

**Comment by jcfr** [comment]
> then we should treat it as a convention.

Agreed.

That said, we will remove the checkbox.

**Comment by fedorov** [comment]
> I never felt that confirmation dialog useful, only when it showed "0 series, 0 studies, ...". I think that dialog can be removed, but an error message on failed import would be still useful.

Let's make sure we talk about the same dialog then!

What I suggested to remove is this popup:

image

I agree confirmation after import is completed is useful!

**Comment by lassoan** [comment]
> I agree confirmation after import is completed is useful!

But make sure there is one popup at the end, not a popup for each directory (as it is the case now when you drag&drop multiple folders from File explorer).

**Comment by jcfr** [comment]
> But make sure there is one popup at the end, not a popup for each directory (as it is the case now when you drag&drop multiple folders from File explorer).

It is also handled.
 
See https://github.com/jcfr/CTK/blob/656a35e7b4cd6924bf4e35cb5f68bf01475b45ea/Libs/DICOM/Widgets/ctkDICOMBrowser.cpp#L719-L735

**Comment by cpinter** [comment]
I haven't tried the branch but as far as I understand based on the discussion this does not address https://issues.slicer.org/view.php?id=4360
I'll accept your decisions here, and later may just make sure the confirmation and the extension suggestion popups appear on the same display. It will solve the main problem there (which was the confusion that after closing the first popup I didn't get back control over Slicer, and took a while to realize that there was another modal dialog on the other screen - too many popups right after one another!).

Thanks!

**Comment by jcfr** [comment]
The confirm dialog has been removed and few bugs were fixed.

Changes are now integrated in https://github.com/commontk/CTK/commit/b1d9fb53fd67488adb63edca42068f7549fee21c

**Pull request merged**
