### PR TITLE
ENH: Optional DICOM tags are updated in database from the first file specifying them

### PR DESCRIPTION
**Pull request by malbi**

### CODE REVIEW

**Comment by lassoan** [comment]
Do you mean that you have found DICOM series where the instances (files) contain inconsistent metadata (some fields are only stored in certain files)?

I think that is a DICOM non-conformance - @pieper can you confirm? If it is a non-conformance then we should not implement any mechanism to deal with that in the DICOM database core, because it would be unsustainable.

Instead, it could be fixed in a pre-processing patching step at the application level; or you can implement this custom logic in a custom displayed field generator rule (see all the rules derived from `ctkDICOMDisplayedFieldGeneratorAbstractRule` as examples).

**Comment by pieper** [comment]
Yes, I believe that any patient, study, series level tags must be consistent at the appropriate levels in order to be conformant dicom.  It doesn't surprise me (much) that there are instances of inconsistency in the wild, but I agree it's probably not common enough to include as a special case here.  Perhaps @malbi can provide more details about where these data came from and why it's important to handle this case.

If these are uncommon research files it would probably be better to add special case to [the dicom patcher](https://slicer.readthedocs.io/en/latest/user_guide/modules/dicompatcher.html).

**Comment by malbi** [comment]
Hi, thanks for the quick answer.
My dataset is an acquisition that is loaded as a unique series (same SeriesInstanceUID for all DICOM). All DICOM that contain actual pixel data all have a SeriesDescription specified but I also got one odd file, with no PixelData, same SeriesInstanceUID but no SeriesDescription specified. If this odd file is imported before actual DICOM with pixel data and SeriesDescription, the field will stay empty as it is not updated after series creation in database. As I'm not at ease with DICOM standard I was not sure if this case was common or not, no need to implement such feature if it's not.
In my case It would be enough to just ignore any file that does not have PixelData during import, I will search how to achieve this or I will use the dicom patcher like you suggest.
Thanks a lot for your guidance.

**Comment by pieper** [comment]
Thanks for the extra information.  It can be hard to deal with all the odd combinations of dicom while keeping the core code efficient and maintainable.  A big problem is that there are no comprehensive test cases so regressions can creep in.

Since many valid dicom instances don't have pixel data we would not want to ignore those.

I'm thinking that if we really want to handle this at the database level we would want to record all variants of series-level attributes as distinct (currently we only store one row in the series table by SeriesInstanceUID for efficiency on the assumption that they are identical per the standard).

For now though if you don't see a lot of this data patching sounds like a better solution.  Or just filtering these no-PixelData instances out of your data if you don't want them anyway.  

By the way, if you determine these are non-standard and problematic you should probably report back to the source of the data so they can fix their system.

**Pull request closed without merging**
