### PR TITLE
BUG: preserve whitespace in console completion

### LINKED ISSUE #751: Python auto-complete does not understand newlines
In Slicer console:

```
>>> for i in range(0,5):
...   n1.GetIJKToRASMatrix()
...   n1.<tab>
  File "<string>", line 1
    _ctkAbstractPythonManager_autocomplete_tmp = n1.GetIJKToRASMatrix()n1
                                                                        ^
SyntaxError: invalid syntax
```

cc @MayeulChassagnard

### PR DESCRIPTION
**Pull request by ihnorton**
Erasing whitespace doesn't make very much sense for any language,
but especially not for python.

Fixes #751

### CODE REVIEW

**Comment by ihnorton** [comment]
fixes issues like:
```

>>> for i in x:
...   dir.__call__()
...   dir.<tab>
  File "<string>", line 1
    _ctkAbstractPythonManager_autocomplete_tmp = dir.__call__()dir
                                                                 ^
SyntaxError: invalid syntax
```

which is caused by deleting all spaces, so the completer tries to operate on a string like `foriinx:dir.__call__()dir.`

**Comment by pieper** [comment]
LGTM

Does anyone know why this erasing white space code was added in the first place?

**Comment by jcfr** [comment]
👍 Makes sense.

For the record, here is the original commit where the code was introduced (see https://github.com/commontk/CTK/pull/688/commits/670b434485690871c59fbea27252ef0083f10fcd)

**Comment by pieper** [comment]
May not matter, but @jcfr, I believe you mean this commit: https://github.com/commontk/CTK/commit/6927617f504b04b4f94eb9cd14e1786b78e964f4

Would be good to know if that example still works with the change.

**Comment by ihnorton** [comment]
There's no completion available for that example either with or without this change. Nor should there be, I think. What would the base object be? Speculatively evaluating a function call after a close-paren `call( ... ).<tab>` seems like it would be a bad idea.

**Comment by lassoan** [comment]
call( ... ).<tab> is the most useful feature of all the Python interactor rework. That's why with all the regressions, the interactor rework was still a very useful development. Do you mean you would want to remove this feature?

Before the Python interactor rework, you had to do this (create a new temporary variable for each paren)
```
n=slicer.getNode('MRHead')
dn=someNode.<tab>GetDisplayNodel()
dn.Set<tab>Color(0,1,0)
...

```
Now it's a much simpler and faster:

`n=slicer.getNode('MRHead').<tab>GetDisplayNode().Set<tab>Color(0,1,0)`

Tab after () does not do any speculation, it does evaluate the expression. If somebody has concerns about this then it could be made configurable, but this feature should remain available and should be enabled by default.

**Comment by jcfr** [comment]
@pieper 

> May not matter, but @jcfr, I believe you mean this commit: 6927617

Good point. I just confirmed it still works:

screenshot from 2017-10-04 09-37-15

**Comment by ihnorton** [comment]
@lassoan I just double-checked, and your example still works fine in Slicer after this change.

It seems like a bad idea because any function with side-effects can cause unexpected behavior, for users who either don't know the API or don't know that <tab> is actually evaluating the expression (in the extreme case, imagine `shutil.rmtree`). IPython has/had a feature like this, but they hid it behind a configuration option  (["that's a somewhat dangerous piece of code and always the source of obscure and hard to understand problems"](https://mail.scipy.org/pipermail/ipython-dev/2016-May/017101.html))

IPython has now deprecated the greedy option in favor of [Jedi](https://github.com/davidhalter/jedi). It would be nice to do the same here, eventually. The results should be pretty good if vtkWrapPython type hints work for Slicer code in VTK8.

Anyway, I had missed that this was even available; obviously it makes some people happy, and I'm not going to push the issue.

**Comment by lassoan** [comment]
I agree that there may be unintended side effects of executing on Tab instead of Enter and I would worry about it very much if this was a generic Python console. However, in case of Slicer's Python console the benefit is huge and the chance of unintended side effects causing problems is really low (mostly due to nature of VTK objects).

**Comment by pieper** [comment]
I'm with Isaiah with this one - I don't like the idea of executing code with side effects during tab completing.  I would much rather see it introspect return types to provide completions.  If we could restrict to only in specific cases like array access, constructors or Get methods with no side effects it might be worth having.

**Comment by jcfr** [comment]
To clarify, evaluation happen only after typing a dot after a callable object and using tab.

We could restrict it to callable objects belonging to Qt, VTK, CTK and Slicer ?  Or looking into integrating Jedi .... 

That said, I don't have the bandwidth to work on this.

**Comment by lassoan** [comment]
Introspection is just a heuristics that work well in simple cases but work very poorly for C++ wrapped classes (based on what I have seen with PyCharm and Eclipse). If we can make it work, it's great, especially for offline code editing, but during debugging I would much prefer actual information.

I agree with the general principle that code should not be executed unless the user asks for it, but:

1. The user actually asks for it by pressing `Tab`. We can educate the users about that both `Tab` and `Enter` executes code.
2. In the context of using Slicer's Python interactor for interacting with MRML nodes and modules, it is really hard to come up with realistic scenarios where executing expressions on `Tab` would cause problems.

Anyway, we can make the option configurable, we just have to agree on what should be the default behavior. Do you see any problem with keeping the current behavior as default (execute on `Tab`)?

**Comment by pieper** [comment]
@jcfr's point is well taken - if it's the case that hitting tab gives you the method followed by (), but then you need to explicitly type a period and then tab to execute the method then it sounds okay.

**Comment by jcfr** [comment]
> if it's the case that hitting tab gives you the method followed by (), but then you need to explicitly type a period and then tab to execute the method then it sounds okay.

See https://github.com/commontk/CTK/blob/f096a15fba0f270879c0d7365941dde0fb56fd2a/Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp#L467-L533

**Pull request merged**
