### PR TITLE
ENH added AccessionNumber to Filters 

### PR DESCRIPTION
**Pull request by rbumm**
This small change adds "AccessionNumber" support in DICOM queries

### CODE REVIEW

**Review by pieper — APPROVED** [review]
LGTM 👍

**Comment by pieper** [comment]
Thanks!  I hope you are finding this code useful.  Small nitpick, it should have had a colon in the commit message ("ENH:" instead of "ENH") but I merged it anyway since that's a very minor point and not worth going back and forth on.

**Comment by jamesobutler** [comment]
A squash and merge would have been a possibility for you to fix that up @pieper on merge

**Comment by pieper** [comment]
Yes, I did try adding the colon during the squash step but it didn't stick.

**Comment by jamesobutler** [comment]
The change is in your merge commit.  It appears you did a merge commit rather than a squash and merge.
```
Merge pull request #987 from rbumm/patch-1

ENH: added AccessionNumber to Filters
```

**Comment by pieper** [comment]
Yes, that sounds right.  I'll keep an eye on that in the future.

**Comment by rbumm** [comment]
Thank you, Steve!

Am Fr., 30. Juli 2021 um 21:35 Uhr schrieb Steve Pieper <
***@***.***>:

**Comment by rbumm** [comment]
Sorry for that. I will add the colons in the future.
Best regards Rudolf

Am Fr., 30. Juli 2021 um 21:57 Uhr schrieb James Butler <
***@***.***>:

**Pull request merged**
