### PR TITLE
XNAT API: Refactor upload and implement file upload

### PR DESCRIPTION
**Pull request by AndreasFetzer**
Here is a short overview about what is changed within this pull request

- Refactored existing upload / save functionality: save() method was moved to ctkXnatObject. Each subclass has now a saveImpl() which is called by save() (similar to the fetch / download functionality)
- Implemented file upload via the CTK XNAT API
- Validation of the upload is done via the XNAT resource catalog xml which is parsed by a new class (ctkXnatResourceCatalogXmlParser)
- Added new class ctkXnatResourceFolder, which is consistent to ctkXnatScanFolder, ctkXnatreconstructionFolder and ctkXnatAssessorFolder
- Implemented resource creation via CTK XNAT API
- Added defaultDownloadDir location to ctkXnatSession
- Updated qRestAPI to latest revision, which supports the file upload
- Enhanced ctkXnatTreeModel so that new children can be added to existing objects
- Enhanced ctkXnatTreeBrowser for resource creation and file upload possibility

### CODE REVIEW

**Comment by jcfr** [comment]
These seems like very good improvement :+1:  

Not being a user of XNAT, I won't be able to provide more comments.

@fedorov What do you think ?

**Comment by espakm** [comment]
I will review it.

**Comment by fedorov** [comment]
I have never used XNAT CTK API. I have some experience with XNAT python API, but I have not used it for a while as well. Overall, XNAT turned out to be too restrictive for our use cases, and the python API had bugs. We are not likely to continue using XNAT at all. Personally, I cannot justify the time to learn and evaluate a C++ API for XNAT, when I know I am not likely to continue using XNAT.

If you would like to get an idea how it maps to a real use case, you can consider looking at this application https://github.com/NrgXnat/XNATSlicer and coordinating with the current support team for that application.

**Comment by jcfr** [comment]
@espakm Thanks for volunteering

@fedorov Thanks for your comment and sorry for the noise. I initially thought that https://github.com/NrgXnat/XNATSlicer was using CTK XNAT objects and widgets.

**Comment by fedorov** [comment]
I think where CTK could really help is in harmonizing APIs and widgets. In QIICR project, we developed TCIABrowser https://github.com/QIICR/TCIABrowser. You can see that Slicer DICOM browser, XNAT browser from the project above, and TCIABrowser visually share a lot of common elements, but there is no common API, and widgets are re-implemented. Would be great to get an opinion from the CTK team. 

@mehrtash is the lead developer for TCIABrowser, and is also very familiar with CTK DICOM widgets, so maybe he can comment here as well. I know this may be a distraction outside the issue topic, let me know if this is not the right place.

**Comment by AndreasFetzer** [comment]
I removed the check for the empty path, but still left the check whether the path exists.

**Comment by espakm** [comment]
Ignore the comments about the modified flag, as it was removed by a later commit, anyway.

**Comment by espakm** [comment]
These are all my comments, mostly questions, except 71a6a8f. It is great, thanks so much!

**Comment by AndreasFetzer** [comment]
Thank you very much for reviewing my pull request, Miklos! I will start working on your remarks immediately.

Regarding the QXmlDefaultHandler:
The QXmlDefaultHandler is part of the Qt Xml module, which is not maintained anymore (at least since Qt 5).
See also: http://doc.qt.io/qt-5/qtxml-index.html
They recommend to use the QXmlStreamReader instead

**Comment by AndreasFetzer** [comment]
I added some bugfixes and also the possibility to force the fetching of xnatObjects as well as a refresh function for the xnatTreeModel.
@espakm it would be great if you could have another look at this. Thanks so much, again!
From my point of view this is done, so I won't add any additional stuff :wink:

**Comment by espakm** [comment]
All looks good now. Ready to merge. Thanks so much!

**Pull request merged**
