### PR TITLE
WIP: add thumbnails to dicom browser

### PR DESCRIPTION
**Pull request by pieper**
Based on ProjectWeek discussion:
https://projectweek.na-mic.org/PW35_2021_Virtual/Projects/mpReview/

### CODE REVIEW

**Comment by pieper** [comment]
Example usage here: https://youtu.be/JsKRAi9E8U0

**Comment by Punzo** [comment]
Hi @pieper what is the status of this PR?

I think it could be very useful. For example the ctkDICOMThumbnailGenerator [method](https://github.com/commontk/CTK/pull/979/files#diff-7cf1b5e1dc93e5126a456b47a9144a67d770afefae5012c9baefbb7c33712f10R203) which returns a QImage removes a performance bottleneck when rendering >30 thumbnails at once. (Saving to png in some cases could take from 0.01 to 0.1 sec for each thumbnail).

Please let me know if I can help with anything in integrating this PR.

**Comment by pieper** [comment]
@Punzo thanks for looking at this.  I think it's ready to go if we like the current functionality but we could always improve things I guess.  I'd be fine with merging it now and then adding improvements in a future PR.

**Comment by Punzo** [comment]
> @Punzo thanks for looking at this. I think it's ready to go if we like the current functionality but we could always improve things I guess. I'd be fine with merging it now and then adding improvements in a future PR.

Perfect, I'll wait the merge then !  Thanks!

**Comment by pieper** [comment]
@lassoan @cpinter Can one of you have a quick look and comment if we should merge as-is to do some more tweaks?

**Comment by jcfr** [comment]
Thanks @Punzo and @pieper 

I will have a look tonight or tomorrow.

**Review by lassoan — COMMENTED** [review]
Looks great, I would just suggest a [few improvements (that I implemented and tested already)](https://github.com/lassoan/CTK/tree/browser-thumbnails):
- Make the layout horizontal (place the image on the right instead of below) as the list tends to be narrow and the tall.
- Add an expand (double-array) button to allow show/hide of the thumbnail.
- Performance improvement: Only update the thumbnail if it is visible. I've also experimented with delayed update of the thumbnail (only updates the thumbnail when the slider does not move for 10ms), but it made it harder to find frames with browsing, so I did not end up adding this feature.

image

**Comment by lassoan** [comment]
@pieper I did not have right to push to your fork, so I've pushed it to my branch: https://github.com/lassoan/CTK/tree/browser-thumbnails

Probably you want to cherry-pick my commits from there. I've also implemented a few small issues.

**Comment by pieper** [comment]
These look great @lassoan 👍 

Mine was just a WIP, so it's just as easy to make a new PR from your branch and work from here.  Then I can retire mine.

**Comment by lassoan** [comment]
I've rebased and cleaned up the branch and submitted the new pull request: https://github.com/commontk/CTK/pull/1063, so I'm closing this one now.

**Pull request closed without merging**
